### ISSUE TITLE
点击列出所有仓库会卡主，后端日志报错如下

### ISSUE THREAD

**Issue by gxxc** [thx/rap2-dolores#43]
<-- GET /account/info
SELECT `id`, `fullname`, `email` FROM `Users` AS `User` WHERE ((`User`.`deletedAt` > '2018-04-27 04:03:05' OR `User`.`deletedAt` IS NULL) AND `User`.`id` = 100000012); ===========
  --> GET /account/info 200 16ms 84b
  <-- GET /app/counter
  --> GET /app/counter 200 2ms 71b
  <-- GET /repository/list?user=&organization=&name=&cursor=1&limit=100

      SELECT COUNT(id) AS num FROM (
        SELECT o.id, o.name
        FROM Organizations o
        WHERE visibility = 1 OR creatorId = 100000012 OR ownerId = 100000012
        UNION
        SELECT o.id, o.name
        FROM Organizations o
        JOIN organizations_members om ON o.id = om.organizationId
        WHERE om.userId = 100000012
      ) as result
      WHERE id =
     ===========

Unhandled rejection SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 7
    at Query.formatError (/root/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:250:16)
    at Query.handler [as onResult] (/root/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/root/rap2-delos/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/root/rap2-delos/node_modules/mysql2/lib/connection.js:504:28)
    at PacketParser.onPacket (/root/rap2-delos/node_modules/mysql2/lib/connection.js:82:13)
    at PacketParser.executeStart (/root/rap2-delos/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/root/rap2-delos/node_modules/mysql2/lib/connection.js:91:29)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:578:20)
From previous event:
    at Query.run (/root/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/root/rap2-delos/node_modules/sequelize/lib/sequelize.js:558:20)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at retryParameters (/root/rap2-delos/node_modules/sequelize/lib/sequelize.js:555:8)
    at /root/rap2-delos/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/root/rap2-delos/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/root/rap2-delos/node_modules/sequelize/lib/sequelize.js:454:12)
    at resolve (/root/rap2-delos/dist/service/organization.js:20:33)
    at new Promise (<anonymous>)
    at Function.canUserAccessOrganization (/root/rap2-delos/dist/service/organization.js:19:16)
    at Function.<anonymous> (/root/rap2-delos/dist/routes/utils/access.js:22:53)
    at Generator.next (<anonymous>)
    at /root/rap2-delos/dist/routes/utils/access.js:6:71
    at new Promise (<anonymous>)
    at __awaiter (/root/rap2-delos/dist/routes/utils/access.js:2:12)
    at Function.canUserAccess (/root/rap2-delos/dist/routes/utils/access.js:20:16)
    at Object.<anonymous> (/root/rap2-delos/dist/routes/repository.js:48:47)
    at Generator.next (<anonymous>)
    at /root/rap2-delos/dist/routes/repository.js:6:71
    at new Promise (<anonymous>)
    at __awaiter (/root/rap2-delos/dist/routes/repository.js:2:12)
    at router_1.default.get (/root/rap2-delos/dist/routes/repository.js:45:51)
    at dispatch (/root/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/root/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /root/rap2-delos/node_modules/koa-router/lib/router.js:346:16

sql是同事帮我打印出来的，好像是少了个id，但是没找到在哪儿配置。
帮忙解决一下3q =。=

**Comment by blackdog1987** [comment]
前端页面用开发者模式打开一下 是请求的哪个url出的问题 把参数一并带上

**Comment by kkroy-zs** [comment]
与[rap2-delos#143](https://github.com/thx/rap2-delos/issues/143)同件
