### ISSUE TITLE
[bug]无法导入特定格式请求参数

### ISSUE THREAD

**Issue by eltonyuen** [thx/rap2-dolores#45]
* 参数示例
```javascript
{
	"params": {
		"userName": "001",
		"page": 1,
		"length": 10
	}
}
```

* 导入结果
![rap_fe_bug](https://user-images.githubusercontent.com/3899936/39734834-8447f1fa-52ab-11e8-8a34-adb0cc42a4da.png)

* 接口异常
```
  SequelizeDatabaseError: Data truncated for column 'type' at row 1
      at Query.formatError (/app/node_modules/_sequelize@4.37.6@sequelize/lib/dialects/mysql/query.js:247:16)
      at Query.handler [as onResult] (/app/node_modules/_sequelize@4.37.6@sequelize/lib/dialects/mysql/query.js:68:23)
      at Query.Command.execute (/app/node_modules/_mysql2@1.5.3@mysql2/lib/commands/command.js:30:12)
      at Connection.handlePacket (/app/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:502:28)
      at PacketParser.onPacket (/app/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:81:16)
      at PacketParser.executeStart (/app/node_modules/_mysql2@1.5.3@mysql2/lib/packet_parser.js:77:14)
      at Socket.<anonymous> (/app/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:89:29)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:280:12)
      at readableAddChunk (_stream_readable.js:265:11)
      at Socket.Readable.push (_stream_readable.js:220:10)
      at TCP.onread (net.js:638:20)

```

**Comment by Bosn** [comment]
统一整理到 https://github.com/thx/rap2-delos/issues/248
