### ISSUE TITLE
登录首页卡住，打开F12报错如下

### ISSUE THREAD

**Issue by coalchan** [thx/rap2-dolores#47]
![image](https://user-images.githubusercontent.com/6671051/39975723-e24426dc-5762-11e8-9f44-60046dd57336.png)

复制代码如下：
`uncaught at e Invariant Violation: Minified React error #105; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=105&args[]=f for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n (http://172.17.8.221:8882/static/js/main.e1326e3e.js:2:27786)
    at d.mountComponent (http://172.17.8.221:8882/static/js/main.e1326e3e.js:40:3767)
    at Object.mountComponent (http://172.17.8.221:8882/static/js/main.e1326e3e.js:7:17346)
    at mountChildren (http://172.17.8.221:8882/static/js/main.e1326e3e.js:41:3240)
    at m._createInitialChildren (http://172.17.8.221:8882/static/js/main.e1326e3e.js:40:17911)
    at mountComponent (http://172.17.8.221:8882/static/js/main.e1326e3e.js:40:16055)
    at Object.mountComponent (http://172.17.8.221:8882/static/js/main.e1326e3e.js:7:17346)
    at mountChildren (http://172.17.8.221:8882/static/js/main.e1326e3e.js:41:3240)
    at m._createInitialChildren (http://172.17.8.221:8882/static/js/main.e1326e3e.js:40:17911)
    at mountComponent (http://172.17.8.221:8882/static/js/main.e1326e3e.js:40:16055)`

**Comment by Bosn** [comment]
需要提供详细的错误，点那个错误链接就可以进入详细错误的提示。
